dist:     alpine
sudo:     required

language: c

os: linux

compiler: gcc

env:
  global:
    - CODECOV_TOKEN="88827976-c055-47f5-8335-5ff14fada8d3"

install:
    - sudo apt-get update
    - sudo apt-get install cmake
    - sudo apt-get install valgrind
    - sudo apt-get install lcov
    # Google tests
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib

before_script:
    - cd /home/travis/build/gavroman/tp_cpp
    - ./3rdparty/linters/run.sh

script:
    - cmake .
    - make
    - ./gtests.out

after_script:
    - lcov --capture --directory ./CMakeFiles/task_library.dir/project/src --output-file coverage.info
    - bash <(curl -s https://codecov.io/bash)

after_success:
    - valgrind valgrind --leak-check=full --show-leak-kinds=all ./gtests.out