dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

install:
    - sudo apt-get update
    - sudo apt-get install libstdc++6

script:
    - ./linters/run.sh
    - cmake .
    - make
