# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gavroman/tp/tp_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gavroman/tp/tp_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gavroman/tp/tp_cpp/CMakeFiles /home/gavroman/tp/tp_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gavroman/tp/tp_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.out

# Build rule for target.
main.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.out
.PHONY : main.out

# fast build rule for target.
main.out/fast:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/build
.PHONY : main.out/fast

project/src/main.o: project/src/main.c.o

.PHONY : project/src/main.o

# target to build an object file
project/src/main.c.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/main.c.o
.PHONY : project/src/main.c.o

project/src/main.i: project/src/main.c.i

.PHONY : project/src/main.i

# target to preprocess a source file
project/src/main.c.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/main.c.i
.PHONY : project/src/main.c.i

project/src/main.s: project/src/main.c.s

.PHONY : project/src/main.s

# target to generate assembly for a file
project/src/main.c.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/main.c.s
.PHONY : project/src/main.c.s

project/src/task.o: project/src/task.c.o

.PHONY : project/src/task.o

# target to build an object file
project/src/task.c.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/task.c.o
.PHONY : project/src/task.c.o

project/src/task.i: project/src/task.c.i

.PHONY : project/src/task.i

# target to preprocess a source file
project/src/task.c.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/task.c.i
.PHONY : project/src/task.c.i

project/src/task.s: project/src/task.c.s

.PHONY : project/src/task.s

# target to generate assembly for a file
project/src/task.c.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/task.c.s
.PHONY : project/src/task.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main.out"
	@echo "... edit_cache"
	@echo "... project/src/main.o"
	@echo "... project/src/main.i"
	@echo "... project/src/main.s"
	@echo "... project/src/task.o"
	@echo "... project/src/task.i"
	@echo "... project/src/task.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

